language: objective-c
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.0
script:
- xcodebuild -project Alamofire-SwiftyJSON.xcodeproj -scheme "AlamofireSwiftyJSON" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty